Add scalafmt/javafmt configuration and scripts

diff --git a/bin/test-code-style b/bin/test-code-style
--- a/bin/test-code-style
+++ b/bin/test-code-style
@@ -8,10 +8,6 @@
 ## Travis and locally).
 ## See https://github.com/lagom/lagom/pull/1482
 
-runSbt  +scalariformFormat \
-        +test:scalariformFormat \
-        multi-jvm:scalariformFormat
-
 runSbt  +headerCheck \
         +test:headerCheck \
         multi-jvm:headerCheck
@@ -25,9 +21,18 @@ runSbt  $EXTRA_TASK \
         validateDependencies \
         mimaReportBinaryIssues
 
+printMessage "VALIDATE SCALA CODE FORMATTING"
+bin/scalafmt --test || (
+  echo "ERROR: Scalafmt test failed, see differences above."
+  echo "To fix, format your sources using bin/scalafmt before submitting a pull request."
+  false
+)
+
+printMessage "VALIDATE JAVA CODE FORMATTING"
+runSbt javafmt
 git diff --exit-code || (
-  echo "ERROR: Scalariform check failed, see differences above."
-  echo "To fix, format your sources using sbt scalariformFormat test:scalariformFormat before submitting a    pull request."
+  echo "[error] ERROR: javafmt check failed, see differences above."
+  echo "[error] To fix, format your sources using sbt javafmt test:javafmt before submitting a pull request."
   false
 )
 
diff --git a/bin/test-documentation b/bin/test-documentation
--- a/bin/test-documentation
+++ b/bin/test-documentation
@@ -14,3 +14,12 @@ fi
 
 cd docs
 runSbt markdownValidateDocs test markdownEvaluateSbtFiles $EXTRA_TASK
+
+printMessage "VALIDATE JAVA CODE FORMATTING FOR DOCS SAMPLE CODE"
+runSbt test:javafmt
+git diff --exit-code || (
+  echo "[error] ERROR: javafmt check failed, see differences above."
+  echo "[error] To fix, before submitting a pull request, format your"
+  echo "[error] sources using sbt javafmt test:javafmt inside docs folder."
+  false
+)
