Revert "Use sbt-scalafmt plugin instead of coursier script"
This reverts commit d476d4ad3ef24f7e139b1dca8b33440b63851d3b.

diff --git a/bin/test-code-style b/bin/test-code-style
--- a/bin/test-code-style
+++ b/bin/test-code-style
@@ -22,7 +22,11 @@ runSbt  $EXTRA_TASK \
         mimaReportBinaryIssues
 
 printMessage "VALIDATE SCALA CODE FORMATTING"
-runSbt scalafmtCheckAll scalafmtSbtCheck
+bin/scalafmt --test || (
+  echo "ERROR: Scalafmt test failed, see differences above."
+  echo "To fix, format your sources using bin/scalafmt before submitting a pull request."
+  false
+)
 
 printMessage "VALIDATE JAVA CODE FORMATTING"
 runSbt javafmt
