Adds scalafmt and javafmt

diff --git a/bin/test-code-style b/bin/test-code-style
--- a/bin/test-code-style
+++ b/bin/test-code-style
@@ -2,18 +2,25 @@
 
 . "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"
 
-runSbt  scalariformFormat \
-        test:scalariformFormat \
-        multi-jvm:scalariformFormat \
-        checkHeaders \
-        test:checkHeaders \
-        multi-jvm:checkHeaders \
-        validateDependencies \
-        mimaCheckOneAtATime
+runSbt checkHeaders \
+       test:checkHeaders \
+       multi-jvm:checkHeaders \
 
+runSbt validateDependencies \
+       mimaCheckOneAtATime
+
+printMessage "VALIDATE SCALA CODE FORMATTING"
+bin/scalafmt --test || (
+  echo "ERROR: Scalafmt test failed, see differences above."
+  echo "To fix, format your sources using bin/scalafmt before submitting a pull request."
+  false
+)
+
+printMessage "VALIDATE JAVA CODE FORMATTING"
+runSbt javafmt
 git diff --exit-code || (
-  echo "ERROR: Scalariform check failed, see differences above."
-  echo "To fix, format your sources using sbt scalariformFormat test:scalariformFormat before submitting a    pull request."
+  echo "[error] ERROR: javafmt check failed, see differences above."
+  echo "[error] To fix, format your sources using sbt javafmt test:javafmt before submitting a pull request."
   false
 )
 
